# Авторизация
<LoginScreen>:

#    MDCard:
#        orientation: "vertical"
#        md_bg_color: 1, 1, 1, 0
#        size_hint: .7, 1
#
#        FitImage:
#            source: "assets/img/auth_bg.png"
#            pos_hint: {"center_x": .93}



    MDFloatLayout:

        MDIconButton:
            icon: "arrow-left"
            style: "standard"
            pos_hint: {"center_x": .07, "center_y": .96}
            on_release: root.manager.current = "welcome"

        MDLabel:
            text: "Авторизация"
            color: "#6A7895"
            theme_font_name: "Custom"
            font_name: "assets/fonts/PTSansCaption-Regular.ttf"
            pos_hint: {"center_x": 0.5, "center_y": 0.83}
            halign: "center"
            font_style: "H5"

        MDFillRoundFlatButton:
            text: "Войти"
            font_style: "H5"
            font_name: "assets/fonts/PTSansCaption-Regular.ttf"
            size_hint: .55, .05
            pos_hint: {"center_x": 0.5, "center_y": 0.3}
            theme_bg_color: "Custom"
            md_bg_color: "#AEC2EC"
            on_release: app.login_user(identifier.text, password.text)

        MDRoundFlatButton:
            text: "Зарегистрироваться"
            line_color: [1, 1, 1, 0]
            text_color: "#97ACD1"
            pos_hint: {"center_x": 0.5, "center_y": 0.23}
            on_release: root.manager.current = "register"

        MDBoxLayout:
            orientation: "vertical"
            size_hint: 0.9, .2
            height: self.minimum_height
            pos_hint: {"center_x": 0.55, "center_y": 0.65}
            spacing: dp(20)
            padding: dp(10)

            MDTextField:
                id: identifier
                hint_text: "*Почта или логин"
                size_hint_x: 0.8

                color_mode: 'Custom'
                line_color_focus: "#6A7895"


            MDBoxLayout:
                orientation: "horizontal"
                size_hint_y: .4


                MDTextField:
                    id: password
                    hint_text: "*Пароль"
                    password: True
                    size_hint_x: 0.8
                    line_color_focus: "#6A7895"

                MDIconButton:
                    id: toggle_password_auth
                    icon: 'eye-off'
                    size_hint_x: 0.2
                    on_release: app.toggle_password_visibility_auth(password, toggle_password_auth)


# Регистрация
<RegisterScreen>:

    MDFloatLayout:

#        MDCard:
#            orientation: "vertical"
#            md_bg_color: 1, 1, 1, 0
#            size_hint: .7, 1
#
#            FitImage:
#                source: "assets/img/auth_bg.png"
#                pos_hint: {"center_x": .93}

        MDLabel:
            text: "Регистрация"
            color: "#6A7895"
            theme_font_name: "Custom"
            font_name: "assets/fonts/PTSansCaption-Regular.ttf"
            pos_hint: {"center_x": 0.5, "center_y": 0.88}
            halign: "center"
            font_style: "H5"
            size_hint: .55, .1

        MDFillRoundFlatButton:
            text: "Зарегистрироваться"
            font_style: "Subtitle1"
            font_name: "assets/fonts/PTSansCaption-Regular.ttf"
            size_hint: .55, .052
            pos_hint: {"center_x": 0.5, "center_y": 0.19}
            theme_bg_color: "Custom"
            md_bg_color: "#AEC2EC"
            on_release: app.register_user(reg_username.text, reg_email.text, reg_password.text, password_repeat.text)

        MDRoundFlatButton:
            text: "Назад ко входу"
            pos_hint: {"center_x": 0.5, "center_y": 0.12}
            line_color: [1, 1, 1, 0]
            text_color: "#97ACD1"
            on_release: root.manager.current = "login"


        MDFloatLayout:
            orientation: "vertical"
            size_hint: 0.9, .45

            pos_hint: {"center_x": 0.55, "center_y": 0.58}

            MDTextField:
                id: reg_username
                hint_text: "*Логин"
                line_color_focus: "#6A7895"
                max_text_length: 20
                size_hint_x: 0.8
                pos_hint: {"center_y": .9, "center_x": 0.4}
            MDTextField:
                id: reg_email
                hint_text: "*Почта"
                line_color_focus: "#6A7895"
                size_hint_x: 0.8
                pos_hint: {"center_y": 0.65, "center_x": 0.4}

            MDBoxLayout:
                orientation: "horizontal"
                size_hint_y: .35
                pos_hint: {"center_y": 0.4, "center_x": 0.5}

                MDTextField:
                    id: reg_password
                    hint_text: "*Пароль"
                    password: True
                    line_color_focus: "#6A7895"
                    size_hint_x: 0.8

                MDIconButton:
                    id: toggle_password_reg
                    icon: 'eye-off'
                    size_hint_x: 0.2
                    on_release: app.toggle_password_visibility_reg(reg_password, password_repeat, toggle_password_reg)

            MDTextField:
                id: password_repeat
                hint_text: "*Повторите пароль"
                password: True
                line_color_focus: "#6A7895"
                size_hint_x: 0.8
                pos_hint: {"center_y": 0, "center_x": 0.4}


# Приветственный экран
<WelcomeScreen>:

    MDScreen:
        md_bg_color: 1, 1, 1, 1

        MDFloatLayout:
            orientation: 'vertical'


            MDCard:
                orientation: "vertical"
                md_bg_color: 1, 1, 1, 0
                pos_hint: {"center_x": .5, "center_y": .62}
                size_hint: 1, .5

                FitImage:
                    source: "assets/img/main2.png"


            MDLabel:
                text: "Добро пожаловать!"
                halign: "center"
                font_style: "H5"
                theme_font_name: "Custom"
                font_name: "assets/fonts/PTSansNarrow-Regular.ttf"
                pos_hint: {"center_x": .5, "center_y": .34}


            MDFillRoundFlatButton:
                text: "Начнем"
                font_style: "H5"
                font_name: "assets/fonts/PTSansCaption-Regular.ttf"
                size_hint: .55, .05
                pos_hint: {'center_x': .5, 'center_y': .2}
                theme_bg_color: "Custom"
                md_bg_color: "#AEC2EC"
                on_release: root.manager.current = "login"
                elevation_levels: dp(12)


# Настройки
<SettingsScreen>:

    MDLabel:
        text: 'Темная тема'
        halign: 'center'
        font_style: "H4"
        pos_hint: {"center_x": .38, "center_y": .513}

    MDSwitch:
        on_active: app.on_switch_active(*args)
        pos_hint: {"center_x": .78, "center_y": .50}
        size_hint_x: .13
        thumb_color_disabled: "#406AAE"
        icon_active: "check"
        icon_inactive: "close"
        icon_inactive_color: "grey"
        track_color_inactive: "#97ACD1"
        thumb_color_active: "lightgrey"

    MDIconButton:
        icon: "arrow-left"
        style: "standard"
        pos_hint: {"center_x": .07, "center_y": .96}
        on_release: root.manager.current = "main"


<AccountScreen>:

    MDFloatLayout:

        MDCard:
            id: mdcard
            orientation: "vertical"
            size_hint: None, None
            size: dp(180), dp(180)
            pos_hint: {"center_x": 0.5, "center_y": .8}
            radius: [dp(100),]

            FitImage:
                id: avatar
                source: "assets/img/avatars/account.png"
                radius: [dp(100),]
                md_bg_color: 1, 1, 1, 0
                #on_touch_down: if self.collide_point(*args[1].pos): app.show_avatar_selection()

    MDLabel:
        id: username_label
        text: '{app.username}'
        halign: "center"
        font_style: "H5"
        theme_font_name: "Custom"
        font_name: "assets/fonts/PTSansNarrow-Regular.ttf"
        theme_text_color: "Custom"
        text_color: "#406AAE"
        pos_hint: {"center_x": .5, "center_y": .6}

    MDLabel:
        id: useremail_label
        text: '{app.username}'
        halign: "center"
        font_style: "H5"
        theme_font_name: "Custom"
        font_name: "assets/fonts/PTSansNarrow-Regular.ttf"
        theme_text_color: "Custom"
        text_color: "#406AAE"
        pos_hint: {"center_x": .5, "center_y": .52}

    MDFillRoundFlatButton:
        text: "Выйти"
        font_style: "H5"
        font_name: "assets/fonts/PTSansCaption-Regular.ttf"
        size_hint: .55, .05
        pos_hint: {'center_x': .5, 'center_y': .2}
        theme_bg_color: "Custom"
        md_bg_color: "#AEC2EC"
        on_release: app.logout_user()  # Вызываем метод выхода из аккаунта
        elevation_levels: dp(12)

    MDIconButton:
        icon: "arrow-left"
        style: "standard"
        pos_hint: {"center_x": .07, "center_y": .96}
        on_release: root.manager.current = "main"


MDScreen:

    MDNavigationLayout:

        MDScreenManager:
            id: screen_manager

            # Приветственный экран
            WelcomeScreen:
                name: "welcome"

            LoginScreen:
                name: "login"

            RegisterScreen:
                name: "register"

            # Главный экран
            MDScreen:
                name: "main"

                # Навигация снизу
                MDBottomNavigation:
                    id: bottom_nav
                    selected_color_background: 0, 0, 0, 0
                    text_color_active: "#13397D"
                    text_color_normal: "#97ACD1"

                    MDBottomNavigationItem:
                        name: 'screen 2'
                        icon: 'microphone-outline'

                        MDIconButton:
                            id: action_button
                            icon: "assets/img/start_record.png"
                            icon_size: "100dp"
                            on_release: app.toggleRecording()

                            pos_hint: {"center_x": 0.5, "center_y": 0.6}

                        MDRoundFlatButton:
                            id: play_button
                            text: 'Прослушать'
                            on_release: app.playRecording()
                            disabled: True
                            pos_hint: {"center_x": 0.5, "center_y": 0.2}
                            size_hint_x: .5
                            line_color: "#13397D"
                            theme_text_color: "Custom"
                            text_color: "#13397D"

                        Label:
                            id: recording_time
                            text: "00:00"
                            pos_hint: {"center_x": 0.5, "center_y": 0.4}
                            size_hint: None, None
                            size: "100dp", "50dp"


                    MDBottomNavigationItem:
                        name: 'screen 3'
                        icon: 'chat-outline'

                        MDBoxLayout:
                            orientation: 'vertical'
                            padding: 0
                            size_hint_y: .9
                            size_hint_x: .9
                            pos_hint: {"center_x": 0.5, "center_y": 0.45}

                            # Список сообщений
                            MDScrollView:
                                do_scroll_x: False
                                MDList:
                                    id: chat_list

                # Иконка меню
                MDIconButton:
                    icon: "menu"
                    style: "standard"
                    pos_hint: {"center_x": .07, "center_y": .96}
                    focus_color: "#97ACD1"
                    on_release: nav_drawer.set_state("toggle")

            # Экран настроек
            SettingsScreen:
                name: "setting"

            # Экран Личного кабинета
            AccountScreen:
                name: "account"


        # Боковая панель
        MDNavigationDrawer:
            id: nav_drawer
            radius: (0, 16, 16, 0)
            panel_color: "#97ACD1"
            md_bg_color: 1, 1, 1, 1

            MDBoxLayout:
                orientation: "vertical"
                spacing: "100dp"
                size_hint: 1, 1

                MDNavigationDrawerMenu:

                    MDRoundFlatIconButton:
                        id: round_flat_icon_button
                        text: "Личный кабинет"
                        icon: "account-circle-outline"
                        size_hint: .55, .5
                        line_color: [0, 0, 0, 0]
                        halign: "left"
                        text_color: "#97ACD1"
                        icon_color: "#406AAE"
                        font_size: "22sp"
                        padding: "20dp"
                        on_release:
                            screen_manager.current = "account"
                            nav_drawer.set_state("close")

                    MDRoundFlatIconButton:
                        text: "Настройки"
                        icon: "cog-outline"
                        size_hint: .55, .5
                        line_color: [0, 0, 0, 0]
                        halign: "left"
                        text_color: "#97ACD1"
                        icon_color: "#406AAE"
                        font_size: "22sp"
                        padding: "20dp"
                        on_release:
                            screen_manager.current = "setting"
                            nav_drawer.set_state("close")

                    MDRoundFlatIconButton:
                        text: "Выход"
                        icon: "exit-to-app"
                        size_hint: .55, .5
                        line_color: [0, 0, 0, 0]
                        halign: "left"
                        text_color: "#97ACD1"
                        icon_color: "#406AAE"
                        font_size: "22sp"
                        padding: "20dp"
                        on_release: app.stop()